name: Bouncing Ball with Gravity
description: Krogla, z nastavljivim radijem, ki se obija znotraj stožca aka. jelke. Tokrat z GRAVITACIJO (integracija rabi nekaj sekund da se predkalkulira trajektorija)

author: Rok

school: Fakulteta za Fiziko in karkol majo čez cesto
