name: Bouncing Balls
description: Več kroglic, ki se odbija znotraj stožca (jelke) in puščajo za sabo sled (POZOR! Vsakič, ko se postavi lučke je treba na novo generirati data.npy)

author: Rok
school: Fakulteta za fiziko in karkoli imajo čez cesto
