name: Bouncing Ball
description: Krogla, z nastavljivim radijem, ki se obija znotraj stožca aka. jelke (integracija rabi nekaj sekund da se predkalkulira trajektorija)

author: Rok

school: Fakulteta za Fiziko in karkol majo čez cesto
