name: Bouncing Ball with Gravity
description: Krogla z nastavljivim radijem, ki se odbija znotraj stožca (jelke), tokrat z gravitacijo

author: Rok
school: Fakulteta za fiziko in karkoli imajo čez cesto
